/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_cordova_plugins_truenative_SMTimerScheduler */

#ifndef _Included_org_apache_cordova_plugins_truenative_SMTimerScheduler
#define _Included_org_apache_cordova_plugins_truenative_SMTimerScheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_cordova_plugins_truenative_SMTimerScheduler
 * Method:    fireTimer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_cordova_plugins_truenative_SMTimerScheduler_fireTimer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
