/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_cordova_plugins_truenative_SMRuntime */

#ifndef _Included_org_apache_cordova_plugins_truenative_SMRuntime
#define _Included_org_apache_cordova_plugins_truenative_SMRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_cordova_plugins_truenative_SMRuntime
 * Method:    setupSpiderMonkey
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_apache_cordova_plugins_truenative_SMRuntime_setupSpiderMonkey
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_apache_cordova_plugins_truenative_SMRuntime
 * Method:    writeJavascript
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_cordova_plugins_truenative_SMRuntime_writeJavascript
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_apache_cordova_plugins_truenative_SMRuntime
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_cordova_plugins_truenative_SMRuntime_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
